layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: gianfranco.gasbarri
  # hackerrank: your_username
  instagram: gincos
  # keybase: your_username
  linkedin: gianfranco-gasbarri
  medium: gincos
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ggasba
  # unsplash: your_username
  # vk: your_username
  website: http://gincos.me
  # youtube: your_username

topics:
  - name: Flutter
    web_url: https://flutter.io/
    image_url: https://venturebeat.com/wp-content/uploads/2019/02/google-flutter-logo-white.png?fit=400%2C200&strip=all

  - name: Artificial Intelligence

  - name: Startup Building
