layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - hello-world

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: gianfranco.gasbarri
  # hackerrank: your_username
  instagram: gincos
  # keybase: your_username
  # mastodon: your_username
  linkedin: gianfranco-gasbarri
  medium: gincos
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ggasba
  # unsplash: your_username
  # vk: your_username
  website: http://gincos.me
  # youtube: your_username

topics:
  - name: Flutter
    web_url: https://flutter.io/
    image_url: https://www.codemate.com/wp-content/uploads/2016/02/flutter-logo-round.png

  - name: Artificial Intelligence
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Machine_Learning_Logo.png

  - name: Startup Building
    image_url: https://svgsilh.com/svg/305335.svg